package com.rl.ecps.sub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-10-29T13:46:51.530+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "EbItemWSServiceService", 
                  wsdlLocation = "http://localhost:8020/ecps-protal/services/publish?wsdl",
                  targetNamespace = "http://service.ws.ecps.rl.com/") 
public class EbItemWSServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.ecps.rl.com/", "EbItemWSServiceService");
    public final static QName EbItemWSServicePort = new QName("http://service.ws.ecps.rl.com/", "EbItemWSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8020/ecps-protal/services/publish?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EbItemWSServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8020/ecps-protal/services/publish?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EbItemWSServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EbItemWSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EbItemWSServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EbItemWSServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EbItemWSServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EbItemWSServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EbItemWSService
     */
    @WebEndpoint(name = "EbItemWSServicePort")
    public EbItemWSService getEbItemWSServicePort() {
        return super.getPort(EbItemWSServicePort, EbItemWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EbItemWSService
     */
    @WebEndpoint(name = "EbItemWSServicePort")
    public EbItemWSService getEbItemWSServicePort(WebServiceFeature... features) {
        return super.getPort(EbItemWSServicePort, EbItemWSService.class, features);
    }

}
