package com.rl.ecps.sub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2019-10-29T13:46:51.502+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://service.ws.ecps.rl.com/", name = "EbItemWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbItemWSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publiclishService", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.sub.PubliclishService")
    @WebMethod
    @ResponseWrapper(localName = "publiclishServiceResponse", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.sub.PubliclishServiceResponse")
    public String publiclishService(
            @WebParam(name = "arg0", targetNamespace = "")
                    Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
