package com.rl.ecps.model;

public class EbArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_AREA.EREA_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    private Long ereaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_AREA.PARENT_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_AREA.EREA_NAME
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    private String ereaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_AREA.AREA_LEVEL
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    private Short areaLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_AREA.EREA_ID
     *
     * @return the value of EB_AREA.EREA_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public Long getEreaId() {
        return ereaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_AREA.EREA_ID
     *
     * @param ereaId the value for EB_AREA.EREA_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public void setEreaId(Long ereaId) {
        this.ereaId = ereaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_AREA.PARENT_ID
     *
     * @return the value of EB_AREA.PARENT_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_AREA.PARENT_ID
     *
     * @param parentId the value for EB_AREA.PARENT_ID
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_AREA.EREA_NAME
     *
     * @return the value of EB_AREA.EREA_NAME
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public String getEreaName() {
        return ereaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_AREA.EREA_NAME
     *
     * @param ereaName the value for EB_AREA.EREA_NAME
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public void setEreaName(String ereaName) {
        this.ereaName = ereaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_AREA.AREA_LEVEL
     *
     * @return the value of EB_AREA.AREA_LEVEL
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public Short getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_AREA.AREA_LEVEL
     *
     * @param areaLevel the value for EB_AREA.AREA_LEVEL
     *
     * @mbggenerated Fri Oct 25 23:05:25 CST 2019
     */
    public void setAreaLevel(Short areaLevel) {
        this.areaLevel = areaLevel;
    }
}